//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronicos_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ofertas
    {
        public int ID_Oferta { get; set; }
        public int Producto_ID { get; set; }
        public int Porcentaje_Desc { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public Nullable<System.DateTime> Fecha_fin { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
