//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronicos_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Ofertas = new HashSet<Ofertas>();
            this.ProductoSucursales = new HashSet<ProductoSucursales>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int ID_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public int Marca_ID { get; set; }
        public int Categoria_ID { get; set; }
        public int Existencia { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public string URL_Imagen { get; set; }
        public string Procesador { get; set; }
        public string RAM { get; set; }
        public string DiscoDuro { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Marcas Marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ofertas> Ofertas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoSucursales> ProductoSucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
