//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronicos_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoSucursales
    {
        public int ID_Existencia_Sucursal { get; set; }
        public int ID_Producto { get; set; }
        public int ID_Sucursal { get; set; }
        public int Existencia { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Sucursales Sucursales { get; set; }
    }
}
