//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronicos_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int ID_Venta { get; set; }
        public int Producto_ID { get; set; }
        public double Ganancia { get; set; }
        public System.DateTime Fecha_Venta { get; set; }
        public Nullable<int> Sucursal_ID { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Sucursales Sucursales { get; set; }
    }
}
